### ISSUE TITLE
Replace CFBundleVersion by CFBundleShortVersionString

### ISSUE THREAD

**Issue by antoinelamy** [mirego/MCKillSwitch#12]
The use of `CFBundleShortVersionString` seems a lot more appropriate than `CFBundleVersion` for the needs of a kill switch.

https://github.com/mirego/MCKillSwitch/blob/0bcb3786005b1a889aa97565cde8ec9c7486dc74/MCKillSwitch/MCKillSwitch.m#L181

*CFBundleVersion*
The build-version-number string for the bundle
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364

*CFBundleShortVersionString*
The release-version-number string for the bundle
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349

Briefly, `CFBundleVersion` represents the build number and changes generally with every published version, including those made by a CI. The Apple guidelines describe this field as conforming to the `major.minor.revision` format and many suggest appending the build number to it (ex: `1.0.2.843`). On the other hand, `CFBundleShortVersionString` represents the marketing version of that build (ex: `1.0.2`). The problem is that Apple themselves doesn't follow their own standard. In fact, most of the apps simply put the build number in the `CFBundleVersion` field and so does `agvtool`, distributed alongside Xcode's command line tools to specifically manipulate the build number.

A good approach would probably be to retrieve the `CFBundleShortVersionString` and optionally append `CFBuildNumber` so we can reference a version as something like `1.0.2 (843)`.

**Comment by p-l** [comment]
I would strongly recommend not to break the previous behaviour and add an initialization parameter where the application can specify its version string. This way existing application remain compatible (as default should revert to the previous implementation) and application choosing to use something else can pick the definition of what the version string should be.
